#!/bin/bash
build/ARM/gem5.opt --outdir=../test_result/20151207/mbll_brp --debug-flags=HAP --debug-file=test_lbm.out --stats-file=wb_cache_mbll_hap.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=8 --l3cache --l3_size=2MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "lbm;" -n 1 > ../test_result/20151207/mbll_brp/wb_energy_cache_mbll_brp.txt

build/ARM/gem5.opt --outdir=../test_result/20151207/mbll_brp --debug-flags=HAP --debug-file=test.out --stats-file=wb_cache_mbll_hap.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=8 --l3cache --l3_size=2MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151207/mbll_brp/wb_energy_cache_mbll_brp.txt

build/ARM/gem5.opt --outdir=../test_result/20151207/mbll_brp_nostream --debug-flags=HAP --debug-file=test_brp_2M.out --stats-file=wb_cache_mbll_hap.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=8 --l3cache --l3_size=2MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151207/mbll_brp_nostream/wb_energy_cache_mbll_brp_2M.txt

build/ARM/gem5.opt --outdir=../test_result/20151216/smwl_hybdip --debug-flags=HAP --debug-file=test_hybdip_2M.out --stats-file=wb_cache_mbll_hap.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=8 --l3cache --l3_size=2MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "soplex;mcf;wrf;lbm;" -n 4 > ../test_result/20151216/smwl_hybdip/wb_energy_cache_smwl_hybdip_2M.txt

