#!/bin/bash

#mkdir ../test_result/20151202/cgbl_no_pcmwrite
#mkdir ../test_result/20151202/cgbl_no_pcmread
#mkdir ../test_result/20151202/cgbl_no_all
#mkdir ../test_result/20151202/cgbl_no_dramread
#mkdir ../test_result/20151202/cgbl_no_dramwrite
#build/ARM/gem5.opt --outdir=../test_result/20151202/cgbl_no_all --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=1MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "cgbl;" -n 1 > ../test_result/20151202/cgbl_no_all/wb_energy_cache_cgbl_hybdip.txt
#build/ARM/gem5.opt --outdir=../test_result/20151202/cgbl_no_pcmread --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=1MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm_nopcmread.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "cgbl;" -n 1 > ../test_result/20151202/cgbl_no_pcmread/wb_energy_cache_cgbl_hybdip.txt
#build/ARM/gem5.opt --outdir=../test_result/20151202/cgbl_no_pcmwrite --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=1MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm_nopcmwrite.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "cgbl;" -n 1 > ../test_result/20151202/cgbl_no_pcmwrite/wb_energy_cache_cgbl_hybdip.txt
#build/ARM/gem5.opt --outdir=../test_result/20151202/cgbl_no_dramread --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=1MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram_nodramread.config  -b "cgbl;" -n 1 > ../test_result/20151202/cgbl_no_dramread/wb_energy_cache_cgbl_hybdip.txt
#build/ARM/gem5.opt --outdir=../test_result/20151202/cgbl_no_dramwrite --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=1MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram_nodramwrite.config  -b "cgbl;" -n 1 > ../test_result/20151202/cgbl_no_dramwrite/wb_energy_cache_cgbl_hybdip.txt

mkdir ../test_result/20151202/mbll_no_pcmwrite
mkdir ../test_result/20151202/mbll_no_pcmread
mkdir ../test_result/20151202/mbll_no_all
mkdir ../test_result/20151202/mbll_no_dramread
mkdir ../test_result/20151202/mbll_no_dramwrite
#build/ARM/gem5.opt --outdir=../test_result/20151202/mbll_no_all --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=4MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151202/mbll_no_all/wb_energy_cache_mbll_hybdip.txt
build/ARM/gem5.opt --outdir=../test_result/20151202/mbll_no_pcmread --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=4MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm_nopcmread.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151202/mbll_no_pcmread/wb_energy_cache_mbll_hybdip.txt
build/ARM/gem5.opt --outdir=../test_result/20151202/mbll_no_pcmwrite --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=4MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm_nopcmwrite.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151202/mbll_no_pcmwrite/wb_energy_cache_mbll_hybdip.txt
build/ARM/gem5.opt --outdir=../test_result/20151202/mbll_no_dramread --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=4MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram_nodramread.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151202/mbll_no_dramread/wb_energy_cache_mbll_hybdip.txt
build/ARM/gem5.opt --outdir=../test_result/20151202/mbll_no_dramwrite --stats-file=wb_cache_lsmc_hybdip.txt configs/example/spec2006.py --caches --l2cache --l2_size=256kB --l2_assoc=1 --l3cache --l3_size=4MB  --cpu-type=detailed --nvmain-start=0GB --nvmain-end=1GB --dram-start=1GB --dram-end=1152MB --nvmain-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Pcm.config --dram-config=/home/xiang/workspace/gem5src/nvmain-test/Config/My_Dram_nodramwrite.config  -b "mcf;bzip2;libquantum;lbm;" -n 4 > ../test_result/20151202/mbll_no_dramwrite/wb_energy_cache_mbll_hybdip.txt
